version: "3.2"
services:
  database:
    container_name: database
    image: mariadb
    networks:
      - database
    volumes:
#      Log File 설정
#      show variables like 'data%';
#      show variables like 'gene%';
#      set global general_log=1;
#      set global general_log_file='mariadb.log';
      - ./docker/mariadb/var/lib/mysql:/var/lib/mysql
    environment:
      - TZ=Asia/Seoul
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=mariadb
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=conference
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "3306:3306"
    restart: always

networks:
  database:
    driver: bridge