server:
  port: 8080

spring:
  thymeleaf:
    mode: HTML
    enabled: true
    encoding: UTF-8

  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://127.0.0.1:3306/conference?characterEncoding=UTF-8
      username: root
      password: mariadb

  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      use-new-id-generator-mappings: false
      ddl-auto: update
    show_sql: false
    generate-ddl: false
    properties:
      hibernate.format_sql: true
    defer-datasource-initialization: true

  security:
    oauth2:
      client:
        registration:

          naver:
            client-id: 8zB5oET8Ard7Wz8_BinX
            client-secret: W7ifs6cPoq
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver

          kakao:
            client-id: 04db4ea0b2738d1e48fcf974a944cc0e
            client-secret: Kvoi5FZ3VL2WWCCeRnTZw5RjllFfcs26
            scope:
              - account_email
              - profile_nickname
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: POST

        provider:

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response